"""End-to-end integration tests for SelectionMaid HTTP adapter.

These tests use the real DocumentConverter (no mocks) and real adversarial
fixtures to verify service reliability under hostile input and concurrent load.

Test coverage:
- Adversarial inputs: corrupt, empty, spoofed, password-protected, large PDFs
- Liveness: /health returns 200 after a failing /ingest request
- Concurrency: 5 simultaneous POST /ingest requests all return 200
- Cleanup audit: /tmp/selectionmaid_* tempfiles are removed after processing

Fixture generation:
  Adversarial fixtures are generated by tests/fixtures/generate_adversarial.py.
  This module ensures fixtures exist before tests run via session-scoped fixtures.

Notes on expected status codes:
  - corrupt.pdf:    magic detects application/octet-stream != application/pdf -> 422
  - empty.pdf:      magic detects application/x-empty != application/pdf       -> 422
  - spoofed.pdf:    magic detects text/plain != application/pdf                -> 422
  - protected.pdf:  passes magic (valid PDF headers), Docling fails to decrypt  -> 500
  - large_sample.pdf: ~40MB < 50MB limit; Docling processes it                -> 200 or 500
  - sample.pdf:     valid PDF, Docling extracts successfully                   -> 200
"""
from __future__ import annotations

import asyncio
import glob
import subprocess
import sys
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import AsyncIterator

import httpx
import pytest
from fastapi import FastAPI

# ---------------------------------------------------------------------------
# Directory constants
# ---------------------------------------------------------------------------

FIXTURES_DIR = Path(__file__).parent.parent.parent / "fixtures"
ADV_DIR = FIXTURES_DIR / "adversarial"


# ---------------------------------------------------------------------------
# Session-scoped fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session", autouse=True)
def ensure_adversarial_fixtures() -> None:
    """Generate adversarial fixtures if they do not exist.

    Runs tests/fixtures/generate_adversarial.py once per test session.
    If generation fails (e.g., missing sample.pdf), the session continues
    and individual tests that depend on missing fixtures will be skipped.
    """
    generator = FIXTURES_DIR / "generate_adversarial.py"
    expected = [
        ADV_DIR / "corrupt.pdf",
        ADV_DIR / "empty.pdf",
        ADV_DIR / "spoofed.pdf",
        ADV_DIR / "protected.pdf",
        ADV_DIR / "large_sample.pdf",
    ]
    # Only re-generate if any fixture is missing
    if all(p.exists() for p in expected):
        return
    result = subprocess.run(
        [sys.executable, str(generator)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        # Non-fatal: individual tests will skip if their fixture is missing
        pass


@pytest.fixture(scope="session")
def real_app() -> FastAPI:
    """Build a FastAPI app wired with the real DocumentConverter.

    The router is included at app construction time (not inside lifespan) so
    that FastAPI's routing layer is ready before the first request arrives.
    This mirrors the pattern used in test_router.py for the concurrency test.

    Docling imports are deferred inside the lifespan body so that model loading
    does not occur during fixture collection.
    """
    from selection_maid.adapters.http.router import build_router
    from selection_maid.config import get_config

    config = get_config()

    # Build the real service using the same wiring as app.py
    from docling.datamodel.base_models import InputFormat
    from docling.datamodel.pipeline_options import PdfPipelineOptions
    from docling.document_converter import (
        DocumentConverter,
        PdfFormatOption,
        WordFormatOption,
    )
    from docling.pipeline.simple_pipeline import SimplePipeline
    from docling.pipeline.standard_pdf_pipeline import StandardPdfPipeline

    from selection_maid.adapters.chunker.markdown import build_markdown_chunker
    from selection_maid.adapters.enricher.default import build_metadata_enricher
    from selection_maid.adapters.extractor.docling import build_docling_adapter
    from selection_maid.adapters.filter.heuristic import build_heuristic_filter
    from selection_maid.service import ExtractionService

    pdf_options = PdfPipelineOptions(
        do_ocr=False,
        do_table_structure=True,
    )
    converter = DocumentConverter(
        allowed_formats=[InputFormat.PDF, InputFormat.DOCX, InputFormat.HTML],
        format_options={
            InputFormat.PDF: PdfFormatOption(
                pipeline_cls=StandardPdfPipeline,
                pipeline_options=pdf_options,
            ),
            InputFormat.DOCX: WordFormatOption(pipeline_cls=SimplePipeline),
        },
    )

    extractor = build_docling_adapter(converter)
    filter_ = build_heuristic_filter(config.filter)
    chunker = build_markdown_chunker(config.chunker)
    enricher = build_metadata_enricher(config.enricher)

    service = ExtractionService(
        extractor=extractor,
        filter_=filter_,
        chunker=chunker,
        enricher=enricher,
    )

    router = build_router(service, config)

    @asynccontextmanager
    async def _lifespan(app: FastAPI) -> AsyncIterator[None]:
        app.state.start_time = datetime.now(timezone.utc)
        yield

    app = FastAPI(lifespan=_lifespan)
    app.include_router(router)

    # httpx.ASGITransport does not trigger the FastAPI lifespan, so we must
    # set app.state.start_time directly here.  The /health endpoint reads
    # request.app.state.start_time (D-86) and would raise AttributeError
    # without this pre-initialization.
    app.state.start_time = datetime.now(timezone.utc)

    return app


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _fixture_or_skip(path: Path) -> bytes:
    """Read fixture file bytes or skip the test if the fixture is missing."""
    if not path.exists():
        pytest.skip(f"Fixture not found: {path}")
    return path.read_bytes()


def _count_selectionmaid_tmpfiles() -> int:
    """Count current /tmp/selectionmaid_* files."""
    return len(glob.glob("/tmp/selectionmaid_*"))


# ---------------------------------------------------------------------------
# Task 1 — E2E integration tests for adversarial inputs
# ---------------------------------------------------------------------------


class TestAdversarialInputs:
    """E2E integration tests: adversarial fixtures against the real service."""

    @pytest.mark.asyncio
    async def test_valid_pdf_returns_200(self, real_app: FastAPI) -> None:
        """A valid sample PDF processed by real Docling returns HTTP 200.

        This is the baseline integration test — verifies the happy path with
        real model inference (no mocks).
        """
        pdf_bytes = _fixture_or_skip(FIXTURES_DIR / "sample.pdf")
        transport = httpx.ASGITransport(app=real_app)
        async with httpx.AsyncClient(
            transport=transport, base_url="http://test"
        ) as client:
            response = await client.post(
                "/ingest",
                files={"file": ("sample.pdf", pdf_bytes, "application/pdf")},
            )
        assert response.status_code == 200
        body = response.json()
        assert "metadata" in body
        assert "chunks" in body

    @pytest.mark.asyncio
    async def test_corrupt_pdf_returns_422(self, real_app: FastAPI) -> None:
        """A corrupt PDF (random bytes) is rejected at the magic-bytes layer (422).

        libmagic detects application/octet-stream for 1KB random bytes,
        which does not match the declared application/pdf -> UPLOAD-002.
        """
        corrupt_bytes = _fixture_or_skip(ADV_DIR / "corrupt.pdf")
        transport = httpx.ASGITransport(app=real_app)
        async with httpx.AsyncClient(
            transport=transport, base_url="http://test"
        ) as client:
            response = await client.post(
                "/ingest",
                files={"file": ("corrupt.pdf", corrupt_bytes, "application/pdf")},
            )
        assert response.status_code == 422
        body = response.json()
        assert body["error"]["code"] == "UPLOAD-002"

    @pytest.mark.asyncio
    async def test_empty_pdf_returns_422(self, real_app: FastAPI) -> None:
        """A 0-byte file with .pdf extension is rejected at the magic-bytes layer (422).

        libmagic returns application/x-empty for an empty buffer, which does
        not match application/pdf -> UPLOAD-002.
        """
        empty_bytes = _fixture_or_skip(ADV_DIR / "empty.pdf")
        transport = httpx.ASGITransport(app=real_app)
        async with httpx.AsyncClient(
            transport=transport, base_url="http://test"
        ) as client:
            response = await client.post(
                "/ingest",
                files={"file": ("empty.pdf", empty_bytes, "application/pdf")},
            )
        assert response.status_code == 422
        body = response.json()
        assert body["error"]["code"] == "UPLOAD-002"

    @pytest.mark.asyncio
    async def test_spoofed_pdf_returns_422(self, real_app: FastAPI) -> None:
        """A plain text file renamed to .pdf is rejected at the magic-bytes layer (422).

        libmagic detects text/plain for the plain text content, which does not
        match the declared application/pdf -> UPLOAD-002.
        """
        spoofed_bytes = _fixture_or_skip(ADV_DIR / "spoofed.pdf")
        transport = httpx.ASGITransport(app=real_app)
        async with httpx.AsyncClient(
            transport=transport, base_url="http://test"
        ) as client:
            response = await client.post(
                "/ingest",
                files={"file": ("spoofed.pdf", spoofed_bytes, "application/pdf")},
            )
        assert response.status_code == 422
        body = response.json()
        assert body["error"]["code"] == "UPLOAD-002"

    @pytest.mark.asyncio
    async def test_protected_pdf_returns_500(self, real_app: FastAPI) -> None:
        """A password-protected PDF passes magic-bytes check but Docling fails (500).

        The protected PDF has valid %PDF magic bytes so it passes Layer 3.
        Docling cannot decrypt the AES-256 payload -> ExtractionError -> HTTP 500.
        """
        protected_bytes = _fixture_or_skip(ADV_DIR / "protected.pdf")
        transport = httpx.ASGITransport(app=real_app)
        async with httpx.AsyncClient(
            transport=transport, base_url="http://test"
        ) as client:
            response = await client.post(
                "/ingest",
                files={"file": ("protected.pdf", protected_bytes, "application/pdf")},
            )
        assert response.status_code == 500
        body = response.json()
        assert "error" in body
        assert "code" in body["error"]

    @pytest.mark.asyncio
    async def test_large_pdf_within_size_limit(self, real_app: FastAPI) -> None:
        """A ~40MB PDF (below the 50MB limit) is accepted and processed.

        The file is within the Content-Length limit so it is not rejected with
        413. Docling may succeed (200) or fail on the concatenated blob (500);
        both outcomes are acceptable — the test only asserts the file was NOT
        rejected by the size or magic validators (status != 413 and != 422).
        """
        large_path = ADV_DIR / "large_sample.pdf"
        if not large_path.exists():
            pytest.skip(f"Fixture not found: {large_path}")
        large_bytes = large_path.read_bytes()
        file_size = len(large_bytes)
        # Sanity: fixture should be above 40MB
        assert file_size > 40 * 1024 * 1024, f"large_sample.pdf too small: {file_size}"
        transport = httpx.ASGITransport(app=real_app)
        async with httpx.AsyncClient(
            transport=transport,
            base_url="http://test",
            timeout=300.0,  # generous timeout for large document processing
        ) as client:
            response = await client.post(
                "/ingest",
                files={"file": ("large_sample.pdf", large_bytes, "application/pdf")},
            )
        # 413 = size-rejected (fail), 422 = magic-rejected (fail)
        assert response.status_code not in (413, 422), (
            f"large_sample.pdf was incorrectly rejected with {response.status_code}: "
            f"{response.text}"
        )


# ---------------------------------------------------------------------------
# Task 1 — Liveness test
# ---------------------------------------------------------------------------


class TestLiveness:
    """Verify /health remains available after processing failures."""

    @pytest.mark.asyncio
    async def test_health_ok_after_failing_ingest(self, real_app: FastAPI) -> None:
        """GET /health returns 200 even after a failed /ingest request.

        Sends a spoofed PDF (guaranteed to trigger 422) and then immediately
        checks /health — the service must still report status 'ok'. This
        verifies that error handling in the ingest path does not corrupt
        application state.
        """
        spoofed_bytes = _fixture_or_skip(ADV_DIR / "spoofed.pdf")
        transport = httpx.ASGITransport(app=real_app)
        async with httpx.AsyncClient(
            transport=transport, base_url="http://test"
        ) as client:
            # Trigger a failure
            bad_response = await client.post(
                "/ingest",
                files={"file": ("spoofed.pdf", spoofed_bytes, "application/pdf")},
            )
            assert bad_response.status_code == 422  # confirm failure occurred

            # Service must still be alive
            health_response = await client.get("/health")
        assert health_response.status_code == 200
        assert health_response.json()["status"] == "ok"


# ---------------------------------------------------------------------------
# Task 2 — Concurrency stress test
# ---------------------------------------------------------------------------


class TestConcurrencyStress:
    """Verify the service handles concurrent requests correctly."""

    @pytest.mark.asyncio
    async def test_concurrency_stress_five_requests(self, real_app: FastAPI) -> None:
        """5 simultaneous POST /ingest requests for sample.pdf all return 200.

        Uses asyncio.gather to fire 5 concurrent requests against the real
        service. All must succeed to verify that:
        - run_in_threadpool correctly offloads CPU-bound Docling work
        - Tempfile handling is thread-safe (each request gets its own file)
        - No shared state is corrupted by concurrent access
        """
        pdf_bytes = _fixture_or_skip(FIXTURES_DIR / "sample.pdf")
        transport = httpx.ASGITransport(app=real_app)

        async def _post_ingest(client: httpx.AsyncClient, idx: int) -> int:
            response = await client.post(
                "/ingest",
                files={
                    "file": (
                        f"sample_{idx}.pdf",
                        pdf_bytes,
                        "application/pdf",
                    )
                },
            )
            return response.status_code

        async with httpx.AsyncClient(
            transport=transport,
            base_url="http://test",
            timeout=300.0,
        ) as client:
            statuses = await asyncio.gather(
                *[_post_ingest(client, i) for i in range(5)]
            )

        failures = [s for s in statuses if s != 200]
        assert not failures, (
            f"Expected all 5 concurrent requests to return 200, "
            f"but got: {list(statuses)}"
        )


# ---------------------------------------------------------------------------
# Task 2 — Tempfile cleanup audit
# ---------------------------------------------------------------------------


class TestTempfileCleanupAudit:
    """Verify that /tmp/selectionmaid_* tempfiles are cleaned up after requests."""

    @pytest.mark.asyncio
    async def test_tempfile_cleanup_audit(self, real_app: FastAPI) -> None:
        """No selectionmaid_* tempfiles remain in /tmp after request completes.

        Records the count of /tmp/selectionmaid_* files before the request and
        verifies the count returns to baseline after the response. Tests both
        success (sample.pdf) and error (spoofed.pdf) paths to ensure the
        finally-block cleanup in the router fires in all cases.
        """
        pdf_bytes = _fixture_or_skip(FIXTURES_DIR / "sample.pdf")
        spoofed_bytes = _fixture_or_skip(ADV_DIR / "spoofed.pdf")
        transport = httpx.ASGITransport(app=real_app)

        async with httpx.AsyncClient(
            transport=transport, base_url="http://test", timeout=120.0
        ) as client:
            # Baseline: how many selectionmaid tempfiles exist right now
            baseline = _count_selectionmaid_tmpfiles()

            # Test cleanup on success path
            success_response = await client.post(
                "/ingest",
                files={"file": ("sample.pdf", pdf_bytes, "application/pdf")},
            )
            after_success = _count_selectionmaid_tmpfiles()

            # Test cleanup on error path (422 — magic rejected, no tempfile created)
            error_response = await client.post(
                "/ingest",
                files={"file": ("spoofed.pdf", spoofed_bytes, "application/pdf")},
            )
            after_error = _count_selectionmaid_tmpfiles()

        assert success_response.status_code == 200, (
            f"Success path returned {success_response.status_code}: {success_response.text}"
        )
        assert error_response.status_code == 422, (
            f"Expected 422 for spoofed PDF, got {error_response.status_code}"
        )

        # After each request, the tempfile count must return to baseline
        assert after_success == baseline, (
            f"Tempfile leak after successful ingest: "
            f"before={baseline}, after={after_success}"
        )
        assert after_error == baseline, (
            f"Tempfile leak after failed ingest: "
            f"before={baseline}, after={after_error}"
        )
